# Site wide configuration

title: Vipul Mishra
locale: en_US
description: NVIDIA DLI, Asst Prof at Bennett University
logo: vipulMishra.jpg
url: https://mishravip.github.io

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]



comments: false

# Site owner
owner:
  name: Vipul Mishra
  avatar: vipulMishra.jpg
  email: vipul.mishra@bennett.edu.in
  disqus-shortname: mishravip
  twitter: way2vipul
  facebook: way2vipul
  github: mishravipul
  stackexchange:
  linkedin: vipul-kumar-mishra-7bb43953
  instagram:
  flickr:
  tumblr: 
  pinterest: way2vipul
  weibo:
  google:
    plus: 
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
